apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1-container
          # Set the image with the dynamically set tag
          image: us-central1-docker.pkg.dev/source-test-project/my-test-registry/myapp1:$(TAG_NAME)
          ports:
            - containerPort: 80
          imagePullPolicy: Always
